/**
 * HTML renderer for the public share page at `GET /r/{slug}`.
 *
 * Hand-rolled HTML — no template engine, no framework. Self-contained
 * CSS in a <style> block so the page loads with zero external requests
 * (good for Lighthouse perf + works behind picky corporate proxies).
 *
 * Brand language matches `hellobooks.ai/for-ai-agents` in tone:
 * professional, white-on-blue accent, clear hierarchy. Severity colours
 * follow the standard band convention (red/orange/amber/grey/blue).
 *
 * Output must be safe — all dynamic strings are escaped via `esc()`.
 */

import type { SharePayload } from './types.js';
import type { DetectionSeverity, DetectionFlag } from '../detection/types.js';

const SEVERITY_COLOURS: Record<DetectionSeverity, string> = {
  critical: '#b91c1c',
  high:     '#dc2626',
  medium:   '#d97706',
  low:      '#6b7280',
  info:     '#2563eb',
};

const SEVERITY_RANK: Record<DetectionSeverity, number> = {
  critical: 0,
  high:     1,
  medium:   2,
  low:      3,
  info:     4,
};

const SIGNUP_URL = 'https://hellobooks.ai/signup';
const MIGRATE_BASE = 'https://hellobooks.ai/migrate';

function migrateUrlForTool(tool: string): string {
  // URL paths match Web-Fire-hellobooks.ai/src/app/migrate/from-<source>/
  // — using the wrong prefix (e.g. /migrate/xero) returns a 404.
  if (tool.includes('Xero')) return `${MIGRATE_BASE}/from-xero`;
  if (tool.includes('Zoho')) return `${MIGRATE_BASE}/from-zoho`;
  if (tool.includes('Wave')) return `${MIGRATE_BASE}/from-wave`;
  // Default for QBO + cross-source tools (variance / compare / migration-estimate
  // pass through the slug embedded in their _branding.upgradeCta — when the
  // share page renders standalone we default to QBO as the most common source).
  return `${MIGRATE_BASE}/from-quickbooks`;
}

export interface RenderOptions {
  /** Public URL of this share page — used in OG tags + the "Copy link" button. */
  shareUrl: string;
}

export function renderSharePage(payload: SharePayload, opts: RenderOptions): string {
  const n = payload.summary.totalFlags;
  const noun = n === 1 ? 'issue' : 'issues';
  const title = `HelloBooks AI — analysis result (${n} ${noun} found)`;
  const generated = new Date(payload.generatedAt).toUTCString();
  const migrateUrl = migrateUrlForTool(payload.tool);

  const flagsSorted = [...payload.flags].sort(
    (a, b) => SEVERITY_RANK[a.severity] - SEVERITY_RANK[b.severity],
  );

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1" />
<title>${esc(title)}</title>
<meta name="robots" content="noindex" />
<meta property="og:title" content="${esc(title)}" />
<meta property="og:description" content="Free analysis by HelloBooks AI Agent. Sign up to bulk-fix or migrate." />
<meta property="og:url" content="${esc(opts.shareUrl)}" />
<meta property="og:type" content="website" />
<style>${BASE_STYLES}</style>
</head>
<body>
<header class="hb-header">
  <div class="hb-brand"><span class="hb-mark"></span>HelloBooks AI Agent</div>
  <a class="hb-cta hb-cta-secondary" href="${esc(SIGNUP_URL)}">Sign up free</a>
</header>

<main class="hb-main">
  <section class="hb-hero">
    <p class="hb-eyebrow">Free analysis · ${esc(payload.sourceLabel)}</p>
    <h1 class="hb-h1">${esc(String(payload.summary.totalFlags))} issue${payload.summary.totalFlags === 1 ? '' : 's'} found in your books</h1>
    <p class="hb-sub">
      Scanned ${esc(String(payload.inputSummary.totalRows))} rows
      across ${esc(String(payload.inputSummary.totalJournals))} journals.
      Generated ${esc(generated)}.
    </p>
    <div class="hb-cta-row">
      <a class="hb-cta hb-cta-primary" href="${esc(migrateUrl)}?ref=${esc(opts.shareUrl)}">Resume with your data in HelloBooks &rarr;</a>
      <a class="hb-cta hb-cta-secondary" href="${esc(SIGNUP_URL)}">Sign up free</a>
    </div>
  </section>

  <section class="hb-summary">
    ${renderSummaryCards(payload)}
  </section>

  <section class="hb-flags">
    <h2 class="hb-h2">All findings</h2>
    ${flagsSorted.map((f) => renderFlag(f)).join('\n')}
    ${flagsSorted.length === 0 ? '<p class="hb-empty">No issues detected. Books look clean!</p>' : ''}
  </section>

  <section class="hb-footer-cta">
    <h2 class="hb-h2">Want to fix these in seconds?</h2>
    <p>HelloBooks AI Agent can bulk-categorise, post adjusting JEs, and migrate your books in one click. Free tier available.</p>
    <a class="hb-cta hb-cta-primary" href="${esc(migrateUrl)}?ref=${esc(opts.shareUrl)}">Open in HelloBooks</a>
  </section>
</main>

<footer class="hb-footer">
  <p>Generated by <a href="https://hellobooks.ai/mcp">HelloBooks AI Agent</a> · This page expires after 7 days.</p>
</footer>
</body>
</html>`;
}

function renderSummaryCards(payload: SharePayload): string {
  const entries: Array<{ label: string; count: number; colour: string }> = [];
  for (const sev of ['critical', 'high', 'medium', 'low', 'info'] as const) {
    const count = payload.summary.bySeverity[sev] ?? 0;
    if (count === 0) continue;
    entries.push({ label: sev, count, colour: SEVERITY_COLOURS[sev] });
  }
  if (entries.length === 0) {
    return '<div class="hb-card hb-card-clean">Clean — zero issues across all checks.</div>';
  }
  return entries
    .map(
      (e) => `<div class="hb-card" style="border-top-color:${e.colour}">
  <div class="hb-card-count">${esc(String(e.count))}</div>
  <div class="hb-card-label">${esc(e.label)}</div>
</div>`,
    )
    .join('\n');
}

function renderFlag(f: DetectionFlag): string {
  const colour = SEVERITY_COLOURS[f.severity];
  const fixable = f.fixableInHellobooks
    ? '<span class="hb-fixable">Fixable in HelloBooks</span>'
    : '<span class="hb-fixable hb-fixable-no">Manual review</span>';
  return `<article class="hb-flag" style="border-left-color:${colour}">
  <header class="hb-flag-head">
    <span class="hb-pill" style="background:${colour}">${esc(f.severity)}</span>
    <span class="hb-cat">${esc(f.category)}</span>
    ${fixable}
  </header>
  <p class="hb-flag-msg">${esc(f.message)}</p>
</article>`;
}

/* ──────────────────────── HTML escaping ────────────────────────── */

export function esc(s: string): string {
  return String(s)
    .replaceAll('&', '&amp;')
    .replaceAll('<', '&lt;')
    .replaceAll('>', '&gt;')
    .replaceAll('"', '&quot;')
    .replaceAll("'", '&#x27;');
}

/* ────────────────────────── Base CSS ───────────────────────────── */

const BASE_STYLES = `
:root {
  --hb-bg: #f8fafc;
  --hb-fg: #0f172a;
  --hb-muted: #64748b;
  --hb-border: #e2e8f0;
  --hb-accent: #2563eb;
  --hb-accent-fg: #ffffff;
}
* { box-sizing: border-box; }
html, body { margin: 0; padding: 0; background: var(--hb-bg); color: var(--hb-fg); font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; line-height: 1.5; }
.hb-header { display: flex; justify-content: space-between; align-items: center; padding: 16px 24px; background: white; border-bottom: 1px solid var(--hb-border); }
.hb-brand { font-weight: 600; display: flex; align-items: center; gap: 8px; }
.hb-mark { display: inline-block; width: 16px; height: 16px; background: var(--hb-accent); border-radius: 4px; }
.hb-main { max-width: 880px; margin: 0 auto; padding: 32px 24px; }
.hb-hero { padding: 32px 0; }
.hb-eyebrow { color: var(--hb-muted); margin: 0 0 8px; font-size: 14px; }
.hb-h1 { font-size: 32px; margin: 0 0 12px; }
.hb-h2 { font-size: 22px; margin: 32px 0 16px; }
.hb-sub { color: var(--hb-muted); margin: 0 0 24px; }
.hb-cta-row { display: flex; gap: 12px; flex-wrap: wrap; }
.hb-cta { display: inline-block; padding: 12px 20px; border-radius: 8px; text-decoration: none; font-weight: 500; }
.hb-cta-primary { background: var(--hb-accent); color: var(--hb-accent-fg); }
.hb-cta-primary:hover { background: #1e40af; }
.hb-cta-secondary { background: white; color: var(--hb-fg); border: 1px solid var(--hb-border); }
.hb-cta-secondary:hover { background: #f1f5f9; }
.hb-summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(140px, 1fr)); gap: 12px; margin: 32px 0; }
.hb-card { background: white; padding: 20px; border-radius: 12px; border-top: 4px solid var(--hb-muted); }
.hb-card-count { font-size: 32px; font-weight: 700; }
.hb-card-label { color: var(--hb-muted); text-transform: capitalize; font-size: 14px; }
.hb-card-clean { padding: 20px; background: white; border-radius: 12px; color: var(--hb-muted); }
.hb-flag { background: white; padding: 16px 20px; border-radius: 8px; border-left: 4px solid var(--hb-muted); margin-bottom: 12px; }
.hb-flag-head { display: flex; gap: 8px; align-items: center; margin-bottom: 8px; flex-wrap: wrap; }
.hb-pill { color: white; padding: 2px 10px; border-radius: 999px; font-size: 12px; text-transform: capitalize; }
.hb-cat { font-size: 12px; color: var(--hb-muted); font-family: ui-monospace, monospace; }
.hb-fixable { font-size: 11px; padding: 2px 8px; border-radius: 4px; background: #ecfdf5; color: #047857; margin-left: auto; }
.hb-fixable-no { background: #fef3c7; color: #92400e; }
.hb-flag-msg { margin: 0; color: var(--hb-fg); }
.hb-empty { color: var(--hb-muted); }
.hb-footer-cta { background: white; padding: 32px; border-radius: 12px; margin-top: 32px; text-align: center; }
.hb-footer { border-top: 1px solid var(--hb-border); padding: 24px; text-align: center; color: var(--hb-muted); font-size: 13px; }
.hb-footer a { color: var(--hb-accent); text-decoration: none; }
@media (max-width: 640px) {
  .hb-h1 { font-size: 24px; }
  .hb-summary { grid-template-columns: 1fr 1fr; }
}
`;
