/**
 * sync-discovered-articles.ts
 *
 * Pulls the full blog URL set from hellobooks.ai/sitemap.xml, slug-derives a
 * title for each, drops anything the curated catalog in src/data/articles.ts
 * already covers, and writes the remainder to src/data/articlesDiscovered.ts.
 *
 * This bakes a static snapshot for offline/cold-start availability. At RUNTIME
 * the same slugs are also federated live by src/articlesFeed.ts (which shares
 * the slug->Article logic in src/lib/blogSitemap.ts), so a freshly-published
 * post shows up in list_articles within ~1h even before this file is regenerated.
 * Re-running this script just refreshes the baked fallback + improves cold-start
 * coverage.
 *
 * Why a separate file: the curated array stays hand-editable (rich excerpts,
 * tags, country relevance), and `discovered` entries are clearly bulk-imported.
 *
 * Run with: `npm run sync:discovered-articles`
 * Reproducible — sitemap order is deterministic and lastmod stamps are stable.
 */

import { writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { CURATED_ARTICLES } from '../src/data/articles.js';
import {
  DEFAULT_SITEMAP_URL,
  parseBlogEntries,
  slugToTitle,
  deriveTags,
  guessCountry,
} from '../src/lib/blogSitemap.js';

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_PATH = join(__dirname, '..', 'src', 'data', 'articlesDiscovered.ts');

async function main(): Promise<void> {
  const res = await fetch(DEFAULT_SITEMAP_URL);
  if (!res.ok) throw new Error(`sitemap fetch failed: HTTP ${res.status}`);
  const xml = await res.text();

  const blogs = parseBlogEntries(xml);

  // Drop slugs already covered by the curated catalog (re-running the script
  // is idempotent — we only ever target slugs absent from CURATED_ARTICLES).
  const curatedIds = new Set(CURATED_ARTICLES.map((a) => a.id));
  const fresh = blogs.filter((b) => !curatedIds.has(b.slug));

  // Sort newest first so the array reads chronologically backwards.
  fresh.sort((a, b) => b.lastmod.localeCompare(a.lastmod));

  const lines: string[] = [];
  lines.push('/**');
  lines.push(' * Auto-discovered blog articles — generated by');
  lines.push(' *   scripts/sync-discovered-articles.ts');
  lines.push(' *');
  lines.push(' * Source of truth: https://hellobooks.ai/sitemap.xml (blog URLs only).');
  lines.push(' * Titles are slug-derived (lower fidelity than the curated catalog in');
  lines.push(' * articles.ts) and every entry carries the `discovered` tag so callers');
  lines.push(' * can distinguish curated flagship content from bulk import.');
  lines.push(' *');
  lines.push(' * This is the BAKED fallback. At runtime src/articlesFeed.ts federates the');
  lines.push(' * same sitemap live, so new posts appear without regenerating this file.');
  lines.push(' * To refresh the baked snapshot: npm run sync:discovered-articles');
  lines.push(' *');
  lines.push(' * Do NOT hand-edit — re-running the script overwrites this file.');
  lines.push(' */');
  lines.push('');
  lines.push("import type { Article } from './articles.js';");
  lines.push('');
  lines.push('export const DISCOVERED_ARTICLES: Article[] = [');
  for (const b of fresh) {
    const title = slugToTitle(b.slug).replace(/'/g, "\\'");
    const tags = deriveTags(b.slug).map((t) => `'${t}'`).join(', ');
    const country = guessCountry(b.slug);
    const excerpt = `${title} — published on hellobooks.ai. Open the article for the full write-up.`.replace(/'/g, "\\'");
    lines.push(
      `  { id: '${b.slug}', title: '${title}', excerpt: '${excerpt}', tags: [${tags}], countryRelevance: '${country}', url: 'https://hellobooks.ai/blog/${b.slug}', publishedAt: '${b.lastmod}', kind: 'blog' },`,
    );
  }
  lines.push('];');
  lines.push('');

  writeFileSync(OUT_PATH, lines.join('\n'), 'utf8');
  process.stdout.write(
    `wrote ${fresh.length} discovered articles to src/data/articlesDiscovered.ts (skipped ${blogs.length - fresh.length} already-curated slugs)\n`,
  );
}

main().catch((err) => {
  process.stderr.write(`sync-discovered-articles failed: ${err instanceof Error ? err.message : String(err)}\n`);
  process.exit(1);
});
